#!/usr/bin/env python
import argparse
import sys
import subprocess
import json
import os

parser = argparse.ArgumentParser(description='Add information with memory bandwidth ceilings measured for the current platform to the json object passed as argument.')
parser.add_argument('json', type=str, nargs='?',
                           help='json object representing the platform information')

args, unknown = parser.parse_known_args()

if args.json == None:
    info = {}
else:
    info = json.loads(args.json)

if !os.path.isfile('bandwidth'):
    print "Could not find 'bandwidth' executable to run test. Make sure the installation script created it."
    sys.exit(1)

print "Obtaining bandwidth ceilings"
status = subprocess.Popen(['./bandwidth', '--fast', '--name', 'Title', '--csv', 'bandwidth.csv'], stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()

# Extract processor cache levels


# Read bandwidth results

# Obtain ceilings per cache levels
tests = {}

# Add information on info object

# Return augmented info object
print json.dumps(info)
