#!/usr/bin/env python
import argparse
import sys
import subprocess
import json
import os

parser = argparse.ArgumentParser(description='Add information with memory bandwidth ceilings measured for the current platform to the json object passed as argument.')
parser.add_argument('json', type=str, nargs='?',
                           help='json object representing the platform information')

args, unknown = parser.parse_known_args()

if args.json == None:
    info = {}
else:
    info = json.loads(args.json)

if not os.path.isfile('bandwidth.json'):
    subprocess.check_call('./install')

    if not os.path.isfile('bandwidth.json'):
        print "Error creating 'bandwidth.json' from ./install script"

info['bandwidth'] = json.load(file('bandwidth.json'))

# Return augmented info object
print json.dumps(info, indent=2)
